### ISSUE TITLE
Bad placement with justify-content: space-*

### ISSUE THREAD

**Issue by csdt** [channingallen/tower-defense#8]
It is impossible to correctly place towers using both `justify-content: space-around;` and `justify-content: space-around;` because of the presence of a non-tower element in the tower-group `div`.

For example, with 2 towers, the second one is always in the middle (with both).

To manually fix this, I had to remove this last element from the div.

**Comment by channingallen** [comment]
> It is impossible to correctly place towers using both justify-content: space-around; and justify-content: space-around;

Do you mean `justify-content: space-around;` and `justify-content: space-between;`? Also, does this bug show up on only on Firefox? If so, I believe this was fixed in commit https://github.com/channingallen/tower-defense/commit/a4cdd87dad4fa15808e03138124c21b610418bac a few days ago.

**Comment by lemaitre** [comment]
I mean `justify-content: space-around;` doesn't work as expected, neither `justify-content: space-between;` does.

I haven't tried with anything else than firefox.
However, this seems to work on http://www.flexboxdefense.com/ now. So it has probably been fixed with the a4cdd87 commit.

Thank you for your answer and keep going, it's a funny project! ;)

**Comment by csdt** [comment]
I mean `justify-content: space-around;` doesn't work as expected, neither does `justify-content: space-between;`.

I haven't tried with anything else than firefox.
However, this seems to work on http://www.flexboxdefense.com/ now. So it has probably been fixed with the a4cdd87 commit.

Thank you for your answer and keep going, it's a funny project! ;)
